### ISSUE TITLE
cannot launch chroma db server in github codespace!

### ISSUE THREAD

**Issue by dodeeric** [dodeeric/langchain-ai-assistant-with-hybrid-rag#56]
nohup chroma run --path ./chromadb &

**Comment by dodeeric** [comment]
@dodeeric ➜ ~ $ /home/codespace/.local/lib/python3.10/site-packages/bin/chroma --help
Traceback (most recent call last):
  File "/home/codespace/.local/lib/python3.10/site-packages/bin/chroma", line 5, in <module>
    from chromadb.cli.cli import app
  File "/home/codespace/.local/lib/python3.10/site-packages/chromadb/__init__.py", line 79, in <module>
    raise RuntimeError(
RuntimeError: Your system has an unsupported version of sqlite3. Chroma                     requires sqlite3 >= 3.35.0.
Please visit                     https://docs.trychroma.com/troubleshooting#sqlite to learn how                     to upgrade.
@dodeeric ➜ ~ $
